site_name: Iris Cobot
site_url: https://iris_cobot.ua.pt/

theme:
    name: readthedocs

markdown_extensions:
  - attr_list

nav:
  - Proposal: index.md
  - Structure: struct.md
  - Introduction: intro.md
  - Background and Related Work: soa.md
  - Collaborative Setup: setup.md
  - Hand Guiding: hand_guide.md
  - Safe Path Planning: safe_planning.md
  - Collaborative Tasks: tasks.md
  - Experiments and Results: results.md
  - Conclusion: conclusion.md
  
  - Extra:
      - Logbook: logbook.md
      - Related Work: related_work.md